#!/usr/bin/env bash
# Port App Manager publication sources. Keep repository identities and derived
# asset URLs here so update, repair, validation, and packaging share one contract.

PAM_GITHUB_WEB_ORIGIN="${PAM_GITHUB_WEB_ORIGIN:-https://github.com}"
PAM_GITHUB_RAW_ORIGIN="${PAM_GITHUB_RAW_ORIGIN:-https://raw.githubusercontent.com}"

PAM_FORK_REPOSITORY="${PAM_FORK_REPOSITORY:-jenny92-tech/PortMaster-GUI}"
PAM_OFFICIAL_REPOSITORY="${PAM_OFFICIAL_REPOSITORY:-PortsMaster/PortMaster-GUI}"
PAM_RUNTIME_REPOSITORY="${PAM_RUNTIME_REPOSITORY:-PortsMaster/PortMaster-New}"
PAM_APPMANAGER_REPOSITORY="${PAM_APPMANAGER_REPOSITORY:-jenny92-tech/portmaster-launcher-pack}"

PAM_FORK_RELEASES_URL="${PAM_FORK_RELEASES_URL:-$PAM_GITHUB_WEB_ORIGIN/$PAM_FORK_REPOSITORY/releases}"
PAM_OFFICIAL_RELEASES_URL="${PAM_OFFICIAL_RELEASES_URL:-$PAM_GITHUB_WEB_ORIGIN/$PAM_OFFICIAL_REPOSITORY/releases}"
PAM_RUNTIME_RELEASES_URL="${PAM_RUNTIME_RELEASES_URL:-$PAM_GITHUB_WEB_ORIGIN/$PAM_RUNTIME_REPOSITORY/releases}"

PAM_CUSTOM_VERSION_URL="${PAM_CUSTOM_VERSION_URL:-$PAM_FORK_RELEASES_URL/latest/download/version.json}"
PAM_OFFICIAL_VERSION_URL="${PAM_OFFICIAL_VERSION_URL:-$PAM_OFFICIAL_RELEASES_URL/latest/download/version.json}"
PAM_DEVICE_CONFIG_URL="${PAM_DEVICE_CONFIG_URL:-$PAM_GITHUB_RAW_ORIGIN/$PAM_APPMANAGER_REPOSITORY/main/config/config.json}"
RUNTIME_METADATA_URL="${RUNTIME_METADATA_URL:-$PAM_RUNTIME_RELEASES_URL/latest/download/ports.json}"
