FROM alpine:3.22

RUN apk add --no-cache \
    binutils \
    build-base \
    cmake \
    file \
    gdb \
    git \
    linux-headers \
    ninja \
    patchelf \
    python3 \
    strace

WORKDIR /work
CMD ["sleep", "infinity"]
