-- Slay the Spire 2 launcher (LÖVE) -- config only; shared skeleton lives in kit.lua.
-- No resolution picker here: sts2 always follows the panel.
-- launch_config.env -> launcher.sh stage-2.

local kit = require("kit")

local LANGUAGES = {"en_US", "zh_CN"}
local QUALITIES = {"smooth", "balanced", "quality"}
local TOGGLES   = {"off", "on"}

local port = {}

port.state = {
    ui_lang = "zh", launch_count = 0,
    language = "zh_CN", quality = "balanced",
    swap_ab = "on", swap_xy = "off",
}

port.strings = {
    title      = {en = "STS2 Linux Launcher", zh = "杀戮尖塔2 启动器"},
    language   = {en = "Language:",  zh = "语言:"},
    quality    = {en = "Quality:",   zh = "画质:"},
    q_smooth   = {en = "Smooth",     zh = "流畅"},
    q_balanced = {en = "Balanced",   zh = "均衡"},
    q_quality  = {en = "Fidelity",   zh = "画质"},
    swap_ab    = {en = "Swap A/B:",  zh = "换 A/B:"},
    swap_xy    = {en = "Swap X/Y:",  zh = "换 X/Y:"},
    english    = {en = "English",    zh = "英文"},
    chinese    = {en = "Chinese",    zh = "中文"},
}

port.credits = {
    {"credit_dev", "Mega Crit"},
    {"credit_porter", "Bili 解腻Jenny"},
}

port.legacy_env = {
    path = "../conf/godot/app_userdata/STS2 Linux Launcher/launch_config.env",
    state_path = "../conf/godot/app_userdata/STS2 Linux Launcher/linux_launcher_state.json",
    fields = {
        language = {name="SLL_LANGUAGE", allowed=LANGUAGES},
        quality = {name="SLL_QUALITY", allowed=QUALITIES},
        swap_ab = {name="SLL_SWAP_AB", allowed=TOGGLES},
        swap_xy = {name="SLL_SWAP_XY", allowed=TOGGLES},
    },
}

local LANG_LABELS = {en_US="english", zh_CN="chinese"}
local QUAL_LABELS = {smooth="q_smooth", balanced="q_balanced", quality="q_quality"}
local TOG_LABELS  = {off="off", on="on"}


function port.build_pages(k, state)
    k.add_page("title", {
        k.picker("language", LANGUAGES, LANG_LABELS, "language"),
        k.picker("quality",  QUALITIES, QUAL_LABELS, "quality"),
        k.picker("swap_ab",  TOGGLES,   TOG_LABELS,  "swap_ab"),
        k.picker("swap_xy",  TOGGLES,   TOG_LABELS,  "swap_xy"),
        k.button("start_game", "start"),
        k.button("quit_menu", "quit"),
    })
end


function port.write_env(f, state, k)
    f:write("# Generated by STS2 love launcher; sourced by launcher.sh on exit 42.\n")
    f:write("SLL_PCK_VARIANT=8x8\n")
    f:write("SLL_LANGUAGE=" .. state.language .. "\n")
    f:write("SLL_QUALITY=" .. state.quality .. "\n")
    f:write("SLL_SWAP_AB=" .. state.swap_ab .. "\n")
    f:write("SLL_SWAP_XY=" .. state.swap_xy .. "\n")
    f:write("SLL_LAUNCH_COUNT=" .. tostring(state.launch_count) .. "\n")
end

kit.run(port)
