#!python
import os

env = SConscript("godot-cpp/SConstruct")

target_path = ARGUMENTS.get("target_path", "bin")
target_name = ARGUMENTS.get("target_name", "godotsteam")

env.Append(CPPPATH=["src"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    os.path.join(target_path, "lib%s%s%s" % (target_name, env["suffix"], env["SHLIBSUFFIX"])),
    source=sources,
)

Default(library)
