#!/usr/bin/env bash
# INPUT:  _kit/recorder.sh 共享录屏引擎与内嵌 CLI 模板
# OUTPUT: tools/record_screen.sh 自包含录屏命令行脚本
# POS:    从唯一维护的录屏引擎生成可复制到设备的 CLI
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
# Copyright (c) 2025-2026 jenny92-tech
#
# Generate the self-contained CLI tool tools/record_screen.sh from the
# canonical engine _kit/recorder.sh. One source of truth; the CLI output can
# be scp'd to a handheld and run over SSH with the recorder ffmpeg beside it.
#
# Usage: _kit/build_recorder_tool.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/tools/record_screen.sh"

{
  cat <<'HEADER'
#!/bin/bash
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
# Copyright (c) 2025-2026 jenny92-tech
#
# record_screen.sh — handheld screen recorder CLI (generated by
# _kit/build_recorder_tool.sh from _kit/recorder.sh — do not edit by hand).
#
# Captures the DRM scanout via ffmpeg kmsgrab at a low framerate to JPEG
# frames (NO video encoding while the game runs), then assembles the frame
# sequence into an MP4. Place this script next to the recorder ffmpeg binary
# and run:
#
#   ./record_screen.sh probe             print environment / feasibility info
#   ./record_screen.sh start             begin 5 fps frame capture (background)
#   ./record_screen.sh status            show active session + frame count
#   ./record_screen.sh stop              stop capture and assemble MP4
#   ./record_screen.sh assemble [DIR]    assemble a session dir into MP4
#
# Environment (all optional): REC_FFMPEG, REC_DIR, REC_FPS, REC_DRM_DEVICE,
# REC_FORMAT, REC_Q, REC_PRESET, REC_CRF, REC_KEEP_FRAMES, REC_LOG_FILE.

set -eu

HEADER
  tail -n +2 "$ROOT/_kit/recorder.sh"
  cat <<'CLI'

# ── CLI ────────────────────────────────────────────────────────────────

case "${1:-}" in
  probe)   recorder_probe ;;
  start)   recorder_start ;;
  stop)    recorder_stop ;;
  status)  recorder_status ;;
  assemble)
    if [ -n "${2:-}" ]; then
      recorder_assemble "$2"
    else
      state="$(recorder_out_dir)/.recorder.state"
      [ -f "$state" ] || { echo "ERROR: no active session (no $state)" >&2; exit 1; }
      # shellcheck disable=SC1090
      . "$state"
      recorder_assemble "$(recorder_out_dir)/${session}"
    fi
    ;;
  *)
    echo "Usage: $0 {probe|start|status|stop|assemble [DIR]}"
    echo "  capture defaults: REC_FPS=${REC_FPS:-5} REC_Q=${REC_Q:-5} REC_DIR=$(recorder_out_dir)"
    exit 1
    ;;
esac
CLI
} > "$OUT"

chmod +x "$OUT"
bash -n "$OUT" || { echo "!! generated tool has syntax errors: $OUT" >&2; exit 1; }
echo ">>> generated $OUT ($(wc -l < "$OUT") lines)"
